import type { Metadata } from "next";
import {  Inter, Lato } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/provider/TanStack-Provider";
import { Toaster } from "sonner";
import AuthProvider from "@/provider/auth-provider";

const inter = Inter({
  subsets: ["latin"],       
  variable: "--font-sans",   
  weight: ["400", "700"],    
});


const lato = Lato({
  subsets: ["latin"],
  variable: "--lato-font",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: " Vendopos",
  description: "Generated by  Vendopos group",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${inter.variable} ${lato.variable} antialiased`}
      >
        <TanstackProvider>
          <AuthProvider>
            
            {children}
            <Toaster position="top-right" richColors />
          </AuthProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
