import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Lato } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/provider/TanStack-Provider";
import { Toaster } from "sonner";
import AuthProvider from "@/provider/auth-provider";

const inter = Inter({
  subsets: ["latin"],        //  only Latin characters
  variable: "--font-sans",   // used in your CSS
  weight: ["400", "700"],    // optional, pick weights you need
});


const lato = Lato({
  subsets: ["latin"],
  variable: "--lato-font",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Vendopos",
  description: "Generated by create Vendopos",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${inter.variable} ${lato.variable} antialiased`}
      >
        <TanstackProvider>
          <AuthProvider>
            
            {children}
            <Toaster position="top-right" richColors />
          </AuthProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
