import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import TanstackProvider from "@/provider/TanStack-Provider";
import { Toaster } from "sonner";
import AuthProvider from "@/provider/auth-provider";
import TopHeader from "@/components/shared/TopHeader";
import Navbar from "@/components/shared/navbar/navbar";


export const metadata: Metadata = {
  title: "Create the VendoPos",
  description: "Generated by create Vendo Group",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased bg-[#F9FFF9]"
        suppressHydrationWarning
      >
      
            <TopHeader />
            <Navbar />
            {children}
         
      
      </body>
    </html>
  );
}
