import type { Metadata } from "next";

import "../globals.css";



import TopHeader from "@/components/shared/TopHeader";
import Navbar from "@/components/shared/navbar/navbar";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "Vendopos",
  description: "Generated by Vendo Group",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-[#F9FFF9] ">
        <TopHeader />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
